# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.9
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: Marvin Weitz
has_binder: false
has_settings: false
kind: frontend
labextension_name: docker_extension
project_short_description: Multiple frontend features for the docker kernel
python_name: docker_extension
repository: ''
test: false

