# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.6
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: import_extension
has_binder: false
has_settings: false
kind: frontend
labextension_name: import_extension
project_short_description: Import Dockerfiles as Notebook
python_name: import_extension
repository: ''
test: false

