# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: weitz_marvin@outlook.de
author_name: Marvin Weitz
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: frontend
labextension_name: shell_extension
mimetype: ''
mimetype_name: ''
project_short_description: 'For Docker Kernel: Control shell of latest image''s container.'
python_name: shell_extension
repository: ''
test: true
viewer_name: ''

